name: Daily Trend Data Update

on:
  schedule:
    # 매일 아침 한국 시간(KST) 오전 8시 30분에 자동 실행 (UTC 23:30)
    - cron: '30 3 * * *'
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # 필요한 라이브러리를 한 번에 설치합니다.
        run: pip install requests pandas

      - name: Run TOP Crawler
        # 깃허브 시크릿을 시스템 환경 변수로 등록합니다.
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_SECRET }}
        run: python trend_crawler.py

      - name: Run AGE Crawler
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_SECRET }}
        run: python age_crawler.py
