name: Naver Kin Crawler Auto Run

on:
  schedule:
    # 매일 오전 3시(한국 시간)에 실행 (UTC 기준 00:00)
    - cron: '0 18 * * *'
  workflow_dispatch: # 직접 실행 버튼을 만들기 위한 옵션

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4 selenium webdriver-manager

      - name: Run Kin Crawler
        run: python kin_crawler.py  # 실행 파일명을 kin_crawler.py로 변경
